name: Tag on Push

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Check commit message for tag
        id: check_message
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          if [[ "$COMMIT_MESSAGE" == *"v"* ]]; then
            echo "::set-output name=tag_message::$COMMIT_MESSAGE"
          else
            echo "No tag found in commit message"
            exit 0
          fi

      - name: Create new tag
        if: steps.check_message.outputs.tag_message
        run: |
          NEW_TAG=$(echo ${{ steps.check_message.outputs.tag_message }} | grep -o 'v[^ ]*')
          git tag -a $NEW_TAG -m "${{ steps.check_message.outputs.tag_message }}"
          git push origin $NEW_TAG